# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
	The artst portfolio website for Ethan Bell
baseurl: "/artst-website" # the subpath of your site, e.g. /blog
url: "https://ethanbell.me" # the base hostname & protocol for your site
twitter_username: #emanb29
github_username:  emanb29

# Build settings
markdown: kramdown
permalink: pretty
